---
- name: Install Jenkins and Docker
  hosts: localhost
  become: yes
  vars:
    jenkins_port: 8080
    jenkins_agent_name: my_agent
    jenkins_admin_username: admin
    jenkins_admin_password: admin123
  tasks:
    - name: Install Docker dependencies
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Jenkins controller
      docker_container:
        name: jenkins_controller
        image: jenkins/jenkins:lts
        restart_policy: always
        ports:
          - "{{ jenkins_port }}:8080"
        volumes:
          - jenkins_home:/var/jenkins_home
          - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml

    - name: Wait for Jenkins to start
      pause:
        seconds: 30

    - name: Install Jenkins agent
      docker_container:
        name: jenkins_agent
        image: jenkins/inbound-agent:latest
        restart_policy: always
        command: "jenkins-agent -url http://jenkins_controller:8080/ {{ jenkins_agent_name }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
