---
- name: Revert Jenkins and Docker Installation
  hosts: localhost
  become: yes
  vars:
    jenkins_port: 8080
    jenkins_agent_name: my_agent
  tasks:
    - name: Stop and remove Jenkins agent container
      command: >
        docker stop jenkins_agent && docker rm jenkins_agent
      ignore_errors: true

    - name: Stop and remove Jenkins controller container
      command: >
        docker stop jenkins_controller && docker rm jenkins_controller
      ignore_errors: true

    - name: Remove Jenkins CLI JAR from Ansible control machine
      file:
        path: jenkins-cli.jar
        state: absent

    - name: Uninstall Docker
      apt:
        name: docker-ce
        state: absent

    - name: Remove Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: absent
