---
- name: Deploy Apache HTTP container
  hosts: localhost
  become: true

  tasks:
    - name: Start Apache HTTP container
      docker_container:
        name: apache_container
        image: httpd
        ports:
          - "80:80"
        restart_policy: always
 
    - name: Create sites-enabled directory
      file:
        path: /etc/apache2/sites-enabled
        state: directory
 
    - name: Configure Apache HTTP as reverse proxy
      copy:
        content: |
          <VirtualHost *:80>
              ProxyPreserveHost On
              ProxyPass / http://jenkins_container:8080/
              ProxyPassReverse / http://jenkins_container:8080/
              ProxyPassMatch ^/(.*?)/?$ http://jenkins_container:8080/$1/ nocanon
              ProxyPassReverse / http://jenkins_container:8080/
          </VirtualHost>
        dest: /etc/apache2/sites-available/reverse-proxy.conf
      notify: Restart Apache

    - name: Enable reverse proxy configuration
      file:
        src: /etc/apache2/sites-available/reverse-proxy.conf
        dest: /etc/apache2/sites-enabled/reverse-proxy.conf
        state: link
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
