---
- name: Install Jenkins and Docker
  hosts: localhost
  become: yes
  vars:
    jenkins_port: 8080
    jenkins_agent_name: my_agent
  tasks:
    - name: Install Docker dependencies
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Jenkins controller
      community.docker.docker_container:
        name: jenkins_controller
        image: jenkins/jenkins:lts
        restart_policy: always
        ports:
          - "{{ jenkins_port }}:8080"
        volumes:
          - jenkins_home:/var/jenkins_home

    - name: Wait for Jenkins to start
      pause:
        seconds: 30

    - name: Get Jenkins CLI JAR
      command: >
        docker cp jenkins_controller:/var/jenkins_home/war/WEB-INF/jenkins-cli.jar jenkins-cli.jar
      args:
        creates: jenkins-cli.jar
      delegate_to: localhost

    - name: Register Jenkins agent
      command: >
        java -jar jenkins-cli.jar -s http://localhost:{{ jenkins_port }}/ create-node {{ jenkins_agent_name }}
      delegate_to: localhost

    - name: Install Jenkins agent
      community.docker.docker_container:
        name: jenkins_agent
        image: jenkins/inbound-agent:latest
        restart_policy: always
        command: "jenkins-agent -url http://jenkins_controller:8080/ {{ jenkins_agent_name }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
