---
- name: Create Jenkins Controller in Docker
  hosts: localhost
  become: true
  vars:
    jenkins_docker_image: jenkins/jenkins:lts
    jenkins_port: 8080
    jenkins_home: /var/jenkins_home
    jenkins_local_user: your_local_user
    jenkins_local_password: your_local_password

  tasks:
    - name: Start Jenkins container
      docker_container:
        name: jenkins_controller
        image: "{{ jenkins_docker_image }}"
        ports:
          - "{{ jenkins_port }}:8080"
        volumes:
          - "{{ jenkins_home }}:/var/jenkins_home"
        detach: yes

    - name: Wait for Jenkins to start
      wait_for:
        host: localhost
        port: "{{ jenkins_port }}"
        state: started
        timeout: 60

    - name: Install Jenkins CLI
      shell: |
        curl -sSL https://get.jenkins.io/war-stable/latest/jenkins.war -o jenkins.war
        cp jenkins.war {{ jenkins_home }}/jenkins.war
      args:
        chdir: "{{ jenkins_home }}"

    - name: Set up Jenkins security
      shell: |
        echo "jenkins.model.Jenkins.instance.securityRealm.createAccount('{{ jenkins_local_user }}', '{{ jenkins_local_password }}')" | java -jar jenkins.war groovy =
      args:
        chdir: "{{ jenkins_home }}"
        executable: /bin/bash

    - name: Restart Jenkins container
      docker_container:
        name: jenkins_controller
        state: restarted
