- name: Install Jenkins Controller with Docker
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Install Docker dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Start Jenkins container
      community.docker.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        restart_policy: always
        ports:
          - "8080:8080"
          - "50000:50000"
        environment:
          - JENKINS_OPTS="--argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin"
        volumes:
          - jenkins_home:/var/jenkins_home
        user: "{{ ansible_user }}"
