---
- name: Install Jenkins controller in Docker and complete initial setup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: create dict
      set_fact:
        dict1: {"var1":"2", "var2":"1"}
    - debug:
        msg: {{ dict1 }}
